exp_id: 002-resnet_t2m_cont
datadir: /data/stephan/WeatherBench/5.625deg/
model_save_dir: /home/rasp/data/myWeatherBench/predictions_S/saved_models/
pred_save_dir: /home/rasp/data/myWeatherBench/predictions_S/
var_dict: {'geopotential': ('z', [50, 250, 500, 600, 700, 850, 925]), 'temperature': ('t', [50, 250, 500, 600, 700, 850, 925]), 'u_component_of_wind': ('u', [50, 250, 500, 600, 700, 850, 925]), 'v_component_of_wind': ('v', [50, 250, 500, 600, 700, 850, 925]), 'specific_humidity': ('q', [50, 250, 500, 600, 700, 850, 925]), '2m_temperature_daily': ('t2m', None), 'constants': ['lsm','orography','lat2d']}
output_vars: [t2m]
filters: [128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 1]
kernels: [7, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]
cont_time: 1
min_lead_time: 732
lead_time: 7320  # 30.5*24*(9+1)
lr: 0.5e-4
early_stopping_patience: 10
reduce_lr_patience: 5
min_es_delta: 0.0001
data_subsample: 24
norm_subsample: 5000
bn_position: post
dropout: 0.1
l2: 1e-5
activation: leakyrelu
nt: 3
loss: lat_mae
batch_size: 32
y_nt: 732  # 30.5 * 24
discard_first: 24
