name: weatherbench_2
channels:
  - conda-forge
dependencies:
  - python=3.6
  - xarray
  - netcdf4
  - dask
  - xesmf
  - fire
  - numpy
  - matplotlib
  - seaborn
  - configargparse
  - tensorflow-gpu=2.2
  - notebook
  - xskillscore
  - pip:
      - cdsapi
