all_years = list(range(1850, 2015))
# all_years = list(range(2000, 2015))

print(config)

rule download:
    output:
          "{dataset}/raw/{name}/{name}_{year}_raw.nc",
    shell:
         "wget http://esg-dn2.nsc.liu.se/thredds/fileServer/esg_dataroot1/cmip6data/CMIP6/CMIP/EC-Earth-Consortium/"
         "EC-Earth3/historical/r1i1p1f1/6hrPlevPt/{config[cmip_name]}/gr/v20200203/{config[cmip_name]}"
         "_6hrPlevPt_EC-Earth3_historical_r1i1p1f1_gr_{wildcards.year}01010000-{wildcards.year}12311800.nc "
         "-O {wildcards.dataset}/raw/{config[name]}/{config[name]}_{wildcards.year}_raw.nc"
         # "wget http://esgf.bsc.es/thredds/fileServer/esg_dataroot/a1u8-CMIP-r20/CMIP6/CMIP/EC-Earth-Consortium/"
         # "EC-Earth3/historical/r20i1p1f1/6hrPlevPt/{config[cmip_name]}/gr/v20191017/"
         # "{config[cmip_name]}_6hrPlevPt_EC-Earth3_historical_r20i1p1f1_gr_"
         # "{wildcards.year}01010000-{wildcards.year}12311800.nc "
         # "-O {wildcards.dataset}/raw/{config[name]}/{config[name]}_{wildcards.year}_raw.nc"

rule regrid:
    input:
          "{dataset}/raw/{name}/{name}_{year}_raw.nc"
    output:
          "{dataset}/{res}deg/{name}/{name}_{year}_{res}deg.nc.tmp"
    shell:
          "python src/regrid.py \
            --input_fns {input} \
            --output_dir {wildcards.dataset}/{wildcards.res}deg/{wildcards.name} \
            --ddeg_out {wildcards.res} \
            --cmip 1 \
            --rename {config[cmip_name]} {config[era_name]} \
            --file_ending nc.tmp"

rule delete:
    input:
          expand("{{dataset}}/{res}deg/{{name}}/{{name}}_{{year}}_{res}deg.nc.tmp",
                 res=config['res']),
    output:
          expand("{{dataset}}/{res}deg/{{name}}/{{name}}_{{year}}_{res}deg.nc",
                 res=config['res'])
    priority: 100
    run:
          for i, o in zip(input, output):
              shell("mv {i} {o}")
          shell("rm {wildcards.dataset}/raw/{wildcards.name}/{wildcards.name}_{wildcards.year}_raw.nc"),


rule all:
    input:
         expand("{datadir}/{res}deg/{name}/{name}_{year}_{res}deg.nc",
                datadir=config['datadir'], res=config['res'], name=config['name'], year=all_years)


