exp_id: 115-resnet_small_multi_dt
datadir: /data/stephan/WeatherBench/5.625deg/
model_save_dir: /home/rasp/data/myWeatherBench/predictions/saved_models/
pred_save_dir: /home/rasp/data/myWeatherBench/predictions/
var_dict: {'geopotential': ('z', [50, 250, 500, 600, 700, 850, 925]), 'temperature': ('t', [50, 250, 500, 600, 700, 850, 925]), 'u_component_of_wind': ('u', [50, 250, 500, 600, 700, 850, 925]), 'v_component_of_wind': ('v', [50, 250, 500, 600, 700, 850, 925]), 'specific_humidity': ('q', [50, 250, 500, 600, 700, 850, 925]), 'constants': ['lsm','orography','lat2d']}
output_vars: [z_*, t_*, u_*, v_*, q_*]
filters: [128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 35]
kernels: [7, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]
lead_time: 12
multi_dt: 2
lr: 0.5e-4
early_stopping_patience: 20
reduce_lr_patience: 5
min_lr_times: 5
reduce_lr_factor: 0.5
#min_es_delta: 0.0001
data_subsample: 2
norm_subsample: 30000
bn_position: post
dropout: 0.1
l2: 1e-5
activation: leakyrelu
nt: 1
loss: lat_mse
batch_size: 32

