exp_id: 002-resnet_prec_tfr
datadir: /data/stephan/WeatherBench/5.625deg/
model_save_dir: /home/rasp/data/myWeatherBench/predictions/saved_models/
pred_save_dir: /home/rasp/data/myWeatherBench/predictions/
var_dict: {'geopotential': ('z', [50, 250, 500, 600, 700, 850, 925]), 'temperature': ('t', [50, 250, 500, 600, 700, 850, 925]), 'u_component_of_wind': ('u', [50, 250, 500, 600, 700, 850, 925]), 'v_component_of_wind': ('v', [50, 250, 500, 600, 700, 850, 925]), 'specific_humidity': ('q', [50, 250, 500, 600, 700, 850, 925]), 'toa_incident_solar_radiation': ('tisr', None), '2m_temperature': ('t2m', None), '6hr_precipitation': ('tp', None), 'constants': ['lsm','orography','lat2d']}
output_vars: [t2m, tp]
filters: [128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 1]
kernels: [7, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]
lead_time: 72
lr: 0.5e-4
early_stopping_patience: 10
reduce_lr_patience: 5
min_es_delta: 0.0001
data_subsample: 1
norm_subsample: 30000
bn_position: post
dropout: 0.1
l2: 1e-5
activation: leakyrelu
nt: 3
dt: 6
loss: lat_mse
batch_size: 32
relu_idxs: 1
tp_log: 0.001
discard_first: 24
tfr_out_idxs: [2, 3]

train_tfr_files: /data/stephan/WeatherBench/TFR/004-era_all/train/*.tfrecord
valid_tfr_files: /data/stephan/WeatherBench/TFR/004-era_all/valid/*.tfrecord
test_tfr_files: /data/stephan/WeatherBench/TFR/004-era_all/test/*.tfrecord
ext_mean: /data/stephan/WeatherBench/TFR/004-era_all/mean.nc
ext_std: /data/stephan/WeatherBench/TFR/004-era_all/std.nc
tfr_num_parallel_calls: 5
tfr_buffer_size: 1000